language: csharp
mono: none
dotnet: 3.1
before_install:
  - cd ./src/api/
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./Project.Hub.Data.Test/Project.Hub.Data.Test.csproj
after_script:
  - cd ../../
