language: csharp
solution: Project.Hub.sln
mono: none
dotnet: 2.1.4
script:
  - cd src
  - dotnet restore
  - dotnet publish ./Project.Hub/Project.Hub.csproj -c Release -o "../../dist/"

before_deploy:
  - cd ../dist
  - ls -als
  - zip project.hub.zip
  - cd ..

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: aws_access_key
  secret_access_key: aws_secret_key
  region: "us-east-2"  
  app: "project.hub"
  env: "projecthub-env"
  bucket_name: "projecthub-env"
  zip_file: "./dist/project.hub.zip"